# Generated by Django 5.0.6 on 2026-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('logo_url', models.URLField(blank=True)),
                ('sla_response_hours', models.IntegerField(default=4, verbose_name='SLA Resposta (horas)')),
                ('sla_resolution_hours', models.IntegerField(default=24, verbose_name='SLA Resolução (horas)')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
