# Generated by Django 5.0.6 on 2026-03-07 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_deadline', models.DateTimeField(verbose_name='Prazo de Resposta')),
                ('resolution_deadline', models.DateTimeField(verbose_name='Prazo de Resolução')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('response_breached', models.BooleanField(default=False, verbose_name='SLA Resposta Estourado')),
                ('resolution_breached', models.BooleanField(default=False, verbose_name='SLA Resolução Estourado')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'SLA',
                'verbose_name_plural': 'SLAs',
            },
        ),
    ]
